services:
    prod:
        profiles:
            - prod
        # Takes 2 arguments in build time (optional values are provided)
        build:
            context: .
            args:
                # These values are used in Dockerfile
                RUN_MODE: PROD
                PORT: 3000
        env_file:
            - ./envs/.env.production.local
        ports:
            - ${PORT:-3000}:${PORT:-3000}

    dev:
        profiles:
            - dev
        build:
            context: .
            args:
                RUN_MODE: DEV
                PORT: 3000
        env_file:
            - ./envs/.env.development.local
        ports:
            - "${PORT:-3000}:${PORT:-3000}" # uygulama portu
            - "9229:9229" # debug portu
        volumes:
            - .:/app:ro
            - /app/node_modules
            - /app/dist
